---
- hosts: all
  become: yes
  become_user: root
  vars:
    logrotate_scripts:
      - name: commcare-sync-logs
        path: "{{ log_dir }}"/*.log
        options:
          - daily
          - weekly
          - size 50M
          - rotate 7
          - missingok
          - compress
          - delaycompress
          - copytruncate
          - notifempty

  roles:
    - ansible-logrotate

  tasks:
    - name: Verify logrotate config check passes
      shell: logrotate -d "{{ logrotate_conf_dir }}{{ item.name }}"
      with_items: "{{ logrotate_scripts }}"
      register: logrotate_tests
    - debug:
        msg: "{{ logrotate_tests }}"

...