---

all:
  vars:
    env: polio
  hosts:
    local1:
      ansible_user: ansible
      ansible_host: 13.244.215.108
      ansible_ssh_private_key_file: /home/ansible/.ssh/polio_rsa.pem
  children:
    commcare_sync:
      hosts:
        local1:

...
