---

all:
  vars:
    env: access-bi
  hosts:
    access-bi:
      ansible_user: dimagi
      ansible_host: 0.tcp.ngrok.io  # 102.16.2.238  not working
      ansible_port: 19464  # 2223 not working
  children:
    commcare_sync:
      hosts:
        access-bi:

...
