---

all:
  vars:
    env: access-bi
  hosts:
    access-bi:
      ansible_user: dimagi
      ansible_host: 102.16.2.238
      ansible_port: 2223
      # ansible_host: 0.tcp.ngrok.io
      # ansible_port: 19464
  children:
    commcare_sync:
      hosts:
        access-bi:

...
