---

ansible_python_interpreter: /usr/bin/python3
base_python_package: "python3"

apt_update_cache: yes

swap_file_enabled: no
swap_file: /swapfile
swap_file_size_kb: 512

app_name: commcare_sync
app_user: "{{ app_name }}"
home_dir: /home/{{ app_user }}
app_group: webapps
project_name: commcare-sync
base_dir: "{{home_dir}}/www"
project_dir: "{{ base_dir }}/{{ project_name }}"
src_dir: "{{ base_dir }}/{{ project_name }}/code_root"
virtualenv_dir: "{{ base_dir }}/.virtualenvs/{{ project_name }}"
virtualenv_python_version: python3.8
requirements_file: "{{ src_dir }}/requirements.txt"
run_dir: "{{ base_dir }}/run"
log_dir: "{{ base_dir }}/log"
static_dir: "{{ src_dir }}/static_root"
media_dir: "{{ src_dir }}/media"

postgresql_version: 10
postgresql_user: postgres

default_db_name: "{{ app_name }}"
default_db_user: "{{ app_name }}"
default_db_password: "{{ vault_default_db_password }}"
default_db_host: 127.0.0.1
default_db_port: 5432

django_settings_module: "{{ app_name }}.settings"
django_migrate: true
django_collectstatic: true

sentry_dsn: "{{ vault_sentry_dsn }}"
mapbox_token: "{{ vault_mapbox_token }}"

app_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"

gunicorn_num_workers: 3
gunicorn_max_requests: 0
gunicorn_reload_workers: true
gunicorn_timeout_seconds: 30

nginx_access_log_file: "{{ log_dir }}/nginx.access.log"
nginx_error_log_file: "{{ log_dir }}/nginx.error.log"

certbot_auto_renew: yes
certbot_script: /opt/certbot-auto
certbot_dir: /etc/letsencrypt
certbot_admin_email: admin@example.com
certbot_domains:
  - example.com
  - www.example.com

...
