---

public_host: 192.168.11.10

app_user: "{{ ansible_user }}"
django_settings_module: "{{ app_name }}.local"

# These variables are normally encrypted and stored in an ansible vault.
vault_default_db_password: commcarehq
vault_mapbox_api_key: fixme
...
