---

public_host: 192.168.11.10
superset_public_host: superset.vagrant.local  # this needs to be manually mapped to 192.168.11.10 in /etc/hosts
superset_enabled: yes

app_user: "{{ ansible_user }}"
django_settings_module: "{{ app_name }}.local"

# These variables are normally encrypted and stored in an ansible vault.
vault_default_db_password: commcarehq
vault_default_superset_password: superset
vault_mapbox_api_key: fixme
...
