---

all:
  vars:
    env: onse
  hosts:
    onse-data-1:
      ansible_user: onse
      ansible_host: 167.71.69.204
      ansible_ssh_private_key_file: ~/.ssh/onse-data_rsa
  children:
    commcare_sync:
      hosts:
        onse-data-1:
...
