---
# if you run playbook using username,password as credentials, set ANSIBLE_HOST_KEY_CHECKING=False
# cmd: export ANSIBLE_HOST_KEY_CHECKING=False

all:
  vars:
    env: aurum
  hosts:
    aurum:
      ansible_user: superadmin
      ansible_host: 10.0.1.15
      ansible_ssh_private_key_file: ~/.ssh/aurum-sync-rsa

  children:
    commcare_sync:
      hosts:
        aurum:

...
