---
#To run playbook using username,password credentials, set ANSIBLE_HOST_KEY_CHECKING=False
# cmd: export ANSIBLE_HOST_KEY_CHECKING=False
#
all:
  vars:
    env: aurum
  hosts:
    aurum:
      ansible_user: "<AURUM_USERNAME>"
      ansible_host: "<AURUM_HOST>"
      ansible_ssh_pass: "<AURUM_USER_PASSWORD>"
  children:
    commcare_sync:
      hosts:
        aurum:

...
