---

all:
  vars:
    env: togo-bi
  hosts:
    togo-bi1:
      ansible_user: ubuntu
      ansible_host: 3.81.231.35
      ansible_ssh_private_key_file: ~/.ssh/Togo.pem
  children:
    commcare_sync:
      hosts:
        togo-bi1:

...
