---

public_host: onse-commcare-sync.dimagi.com
superset_public_host: onse-superset.dimagi.com
ssl_enabled: yes
superset_enabled: yes
superset_ssl_enabled: yes

app_user: "{{ ansible_user }}"
django_settings_module: "{{ app_name }}.local"

project_timezone: "Africa/Johannesburg"
commcare_sync_export_periodicity: 28800  # 60 * 60 * 8 = every 8 hours

...
