---

public_host: 10.0.1.15
superset_public_host: superset.vagrant.local  # this needs to be manually mapped to 192.168.11.10 in /etc/hosts
superset_enabled: no

app_user: "{{ ansible_user }}"
django_settings_module: "{{ app_name }}.local"

...
